// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYB8StEmGtSZauWpVaTMZVcHTGcIUs1oo',
    appId: '1:543630875956:android:a94bef3f43d36db71b9961',
    messagingSenderId: '543630875956',
    projectId: 'whatsapp-messenger-12afe',
    databaseURL: 'https://whatsapp-messenger-12afe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whatsapp-messenger-12afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx3pTvAG2RK501HRrKRCbQ-gVqf5BZ34E',
    appId: '1:543630875956:ios:97f549f195e09e521b9961',
    messagingSenderId: '543630875956',
    projectId: 'whatsapp-messenger-12afe',
    databaseURL: 'https://whatsapp-messenger-12afe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'whatsapp-messenger-12afe.appspot.com',
    iosBundleId: 'com.example.whatsAppClone',
  );
}
